//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTAS
    {
        public decimal ID_OFERTAS { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PORCENTAJE_DESCUENTO { get; set; }
        public decimal PRODUCTOS_ID_PRODUCTOS { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
