//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_VENTA
    {
        public decimal ID_ORDEN { get; set; }
        public Nullable<decimal> FOLIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public decimal PRODUCTOS_ID_PRODUCTOS { get; set; }
        public decimal TIENDA_ID_TIENDA { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual TIENDA TIENDA { get; set; }
    }
}
