//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIENDA
    {
        public TIENDA()
        {
            this.CAMPAIGN = new HashSet<CAMPAIGN>();
            this.ORDEN_VENTA = new HashSet<ORDEN_VENTA>();
            this.PRODUCTOS = new HashSet<PRODUCTOS>();
            this.TRABAJADOR = new HashSet<TRABAJADOR>();
        }
    
        public decimal ID_TIENDA { get; set; }
        public string NOMBRE_TIENDA { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public decimal CIUDAD_ID_CIUDAD { get; set; }
    
        public virtual ICollection<CAMPAIGN> CAMPAIGN { get; set; }
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ICollection<ORDEN_VENTA> ORDEN_VENTA { get; set; }
        public virtual ICollection<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual ICollection<TRABAJADOR> TRABAJADOR { get; set; }
    }
}
